"""
query_processor.py — Intent detection + HyDE for GitHub RAG
════════════════════════════════════════════════════════════
Intent labels
  "explain"  → user wants a walkthrough of how something works
  "design"   → architecture / trade-offs / why questions
  "find"     → locate a function, file, or specific value
  "general"  → everything else

HyDE (Hypothetical Document Embeddings)
  Only applied for "explain" intent.
  A short hypothetical code snippet is generated by llama-3.1-8b-instant
  (fast, cheap) and embedded; the resulting vector better matches dense
  code chunks than the raw question vector.
"""

from __future__ import annotations

import re

# ── Intent keyword tables ─────────────────────────────────────────────────────

_EXPLAIN_KW = re.compile(
    r"\b(explain|how does|how do|walk me through|describe|what does|"
    r"what is|overview|summarize|tell me about)\b",
    re.IGNORECASE,
)

_DESIGN_KW = re.compile(
    r"\b(why|design|architecture|tradeoffs?|trade-offs?|when should|"
    r"pros? and cons?|compare|versus|vs\.?|best practice|pattern)\b",
    re.IGNORECASE,
)

_FIND_KW = re.compile(
    r"\b(find|where is|where are|show me|locate|which file|which function|"
    r"what file|look for|search for|list all)\b",
    re.IGNORECASE,
)

# ── HyDE prompt ───────────────────────────────────────────────────────────────

_HYDE_SYSTEM = (
    "You are a senior software engineer. "
    "Given a question about a codebase, write a SHORT (8-15 lines) hypothetical "
    "code snippet or function that would directly answer or implement what is asked. "
    "Output ONLY the code — no explanations, no markdown fences."
)


# ══════════════════════════════════════════════════════════════════════════════
# Public API
# ══════════════════════════════════════════════════════════════════════════════

def detect_intent(question: str) -> str:
    """
    Classify the question into one of four intent buckets.
    Priority order: explain → design → find → general.
    """
    if _EXPLAIN_KW.search(question):
        return "explain"
    if _DESIGN_KW.search(question):
        return "design"
    if _FIND_KW.search(question):
        return "find"
    return "general"


def generate_hyde_snippet(question: str, groq_client) -> str:
    """
    Generate a hypothetical code snippet for the given question using
    llama-3.1-8b-instant (fast + free tier).  Returns the snippet text,
    or an empty string on failure (caller falls back to raw question).
    """
    try:
        resp = groq_client.chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[
                {"role": "system",  "content": _HYDE_SYSTEM},
                {"role": "user",    "content": question},
            ],
            temperature=0.3,
            max_tokens=256,
        )
        snippet = resp.choices[0].message.content.strip()
        # Strip accidental markdown fences
        snippet = re.sub(r"^```[\w]*\n?", "", snippet)
        snippet = re.sub(r"\n?```$",      "", snippet)
        return snippet.strip()
    except Exception:
        return ""


def process_query(question: str, groq_client=None) -> dict:
    """
    Full query pre-processing pipeline.

    Returns
    -------
    dict with keys:
      intent    str   — "explain" | "design" | "find" | "general"
      use_hyde  bool  — True when HyDE should be used for dense retrieval
      hyde_text str   — the hypothetical snippet (empty if not used)
    """
    intent   = detect_intent(question)
    use_hyde = intent == "explain" and groq_client is not None

    hyde_text = ""
    if use_hyde:
        hyde_text = generate_hyde_snippet(question, groq_client)
        if not hyde_text:
            use_hyde = False

    return {
        "intent":    intent,
        "use_hyde":  use_hyde,
        "hyde_text": hyde_text,
    }
